version: '3.4'

services:
  3cxcdrtcpserver:
    image: 3cxcdrtcpserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SERVER_PORT=5000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=3cxcdr
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
