version: '3.3'

services:
  3cxcdrtcpserver:
    image: 3cxcdrtcpserver
    hostname: 3cxtcpsrv
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && python runserver.py"
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SERVER_PORT=${SERVER_PORT}
      - TZ=Europe/Paris
    depends_on:
      - db

  db:
    hostname: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Paris
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - TZ=Europe/Paris
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data

volumes:
  pgdata: {}
  pgadmin_data: {}


