version: '3.3'

services:
  db:
    hostname: db
    image: postgres:12
    build:
      context: .
      dockerfile: ./db_init/Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    depends_on:
      - db
    ports: 
      - 8004:8000
    container_name: webapi
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn webapi.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"

  ui:
    build: 
      context: .
      dockerfile: ./ui/Dockerfile
    depends_on:
      - webapi
    ports: 
        - 8501:8501
    container_name: ui

  3cxcdrtcpserver:
    image: 3cxcdrtcpserver
    hostname: 3cxtcpsrv
    build:
      context: .
      dockerfile: ./tcpsrv/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - webapi


  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
volumes:
   pgdata: {}
   pgadmin_data: {}




