version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: ./db_folder/Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - 8004:8000
    command: bash -c  "/wait && alembic upgrade head && uvicorn webapi.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    #"while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn webapi.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    environment:
      - WAIT_HOSTS=${POSTGRES_SERVER}:${POSTGRES_PORT}
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    healthcheck:
      test: curl ${API_URL}/healthcheck || exit 1 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  ui:
    build: 
      context: .
      dockerfile: ./ui/Dockerfile
    restart: always
    depends_on:
      webapi:
        condition: service_healthy
    ports: 
        - 8501:8501

  3cxcdrtcpserver:
    image: 3cxcdrtcpserver
    build:
      context: .
      dockerfile: ./tcpsrv/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      webapi:
        condition: service_healthy
    command: bash -c "/wait && python ./tcpsrv/runserver.py"
    environment:
      - WAIT_HOSTS=${POSTGRES_SERVER}:${POSTGRES_PORT}
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}


  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5555:80
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
volumes:
   pgdata: {}
   pgadmin_data: {}




