version: '3.3'

services:
  3cxcdrtcpserver:
    image: 3cxcdrtcpserver
    hostname: 3cxtcpsrv
    build:
      context: .
      dockerfile: ./tcpsrv/Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && python ./tcpsrv/runserver.py"
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db

  db:
    hostname: db
    image: postgres:12
    build:
      context: .
      dockerfile: ./db_init/Dockerfile
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data

  grafana:
    image: grafana/grafana-oss
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  pgdata: {}
  pgadmin_data: {}
  grafana-storage: {}


