version: '3.3'

services:
  3cxcdrtcpserver:
    image: 3cxcdrtcpserver
    hostname: 3cxtcpsrv
    build:
      context: .
      dockerfile: ./tcpsrv/Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && python ./tcpsrv/runserver.py"
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata: {}
  pgadmin_data: {}
  grafana-storage: {}


